server:
  port: 7003

eureka:
  instance:
    hostname: server3
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server1:7001/eureka,http://server2:7002/eureka
